### ISSUE TITLE
why it's not Swift ? 

### ISSUE THREAD

**Issue by abdualrhmanIO** [payfort/start-ios-sdk#1]
I think you should use SWIFT language because the most developers are transferring from Objective-C TO Swift!

**Comment by alovak** [comment]
It was a tough decision for us. I think it's really hard to satisfy different tastes :)
But you are welcome to improve what we have.

**Comment by vsiniak** [comment]
We considered this option with @alovak and decided to use Objective-C, because generally it requires less time for support (Swift is being updated continuously and requires some changes in the code) and at the same time Objective-C allows writing Swift-compatible code, so swift-developers can use Objective-C frameworks (and vice versa).

**Comment by abdualrhmanIO** [comment]
nice
ok for that you have to make things clear by adding swift code examples

 thank you :)
